name: Tests

on:
  push:
    branches:
      - typescript
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - typescript
    paths-ignore:
      - '**.md'

jobs:
  test-coverage:
    name: Run tests

    if: github.event.push || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Installing Dependencies
        run: npm install

      - name: Running Tests
        run: npm run test

      - name: Posting Coverages
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
